/**
 * OmniCalc Pro - Computation Export & Reporting Engine
 *
 * Supports:
 * - Formatted LaTeX equations ready for papers and docs
 * - PDF-ready formatted print calculation sheets
 * - Markdown calculation sheets with metadata and step derivations
 * - CSV data tables for matrices, tables, iterations, and statistics
 * - JSON computation snapshots
 */

export interface ExportReportData {
  title: string;
  engine: string;
  timestamp: number;
  inputDescription: string;
  resultSummary: string;
  latex?: string;
  steps?: string[];
  tableHeaders?: string[];
  tableRows?: (string | number)[][];
  metadata?: Record<string, string | number>;
}

/**
 * Generate formal LaTeX snippet from calculation data
 */
export function generateLatexSnippet(data: ExportReportData): string {
  if (data.latex) {
    return `% OmniCalc Pro Export - ${data.title}
% Date: ${new Date(data.timestamp).toISOString()}
\\begin{equation}
  ${data.latex}
\\end{equation}
`;
  }

  return `% OmniCalc Pro Export - ${data.title}
\\text{${data.engine}}: \\quad ${data.inputDescription} \\implies ${data.resultSummary}
`;
}

/**
 * Generate formatted Markdown document
 */
export function generateMarkdownReport(data: ExportReportData): string {
  const dateStr = new Date(data.timestamp).toLocaleString();
  let md = `# ${data.title} - OmniCalc Pro Report\n\n`;
  md += `**Engine:** ${data.engine}  \n`;
  md += `**Generated:** ${dateStr}  \n\n`;
  md += `---\n\n`;

  md += `## 1. Problem Specification\n`;
  md += `- **Input / Configuration:** \`${data.inputDescription}\`\n`;
  md += `- **Computed Result:** **\`${data.resultSummary}\`**\n\n`;

  if (data.latex) {
    md += `### LaTeX Mathematical Representation\n\`\`\`latex\n${data.latex}\n\`\`\`\n\n`;
  }

  if (data.metadata && Object.keys(data.metadata).length > 0) {
    md += `### Parameters & Metrics\n`;
    Object.entries(data.metadata).forEach(([k, v]) => {
      md += `- **${k}:** \`${v}\`\n`;
    });
    md += `\n`;
  }

  if (data.steps && data.steps.length > 0) {
    md += `## 2. Step-by-Step Derivation\n`;
    data.steps.forEach((step, idx) => {
      md += `${idx + 1}. ${step}\n`;
    });
    md += `\n`;
  }

  if (data.tableHeaders && data.tableRows && data.tableRows.length > 0) {
    md += `## 3. Computation Data Table\n\n`;
    md += `| ${data.tableHeaders.join(' | ')} |\n`;
    md += `| ${data.tableHeaders.map(() => '---').join(' | ')} |\n`;
    data.tableRows.forEach((row) => {
      md += `| ${row.join(' | ')} |\n`;
    });
    md += `\n`;
  }

  md += `---\n*Generated by OmniCalc Pro Enterprise Mathematical Suite*\n`;
  return md;
}

/**
 * Generate Standard CSV formatted text
 */
export function generateCSV(headers: string[], rows: (string | number)[][]): string {
  const escapeCell = (val: string | number) => {
    const s = String(val);
    if (s.includes(',') || s.includes('"') || s.includes('\n')) {
      return `"${s.replace(/"/g, '""')}"`;
    }
    return s;
  };

  const headerLine = headers.map(escapeCell).join(',');
  const rowLines = rows.map((r) => r.map(escapeCell).join(','));
  return [headerLine, ...rowLines].join('\n');
}

/**
 * Trigger browser file download (Markdown, CSV, LaTeX, JSON)
 */
export function downloadTextFile(
  filename: string,
  content: string,
  mimeType: string = 'text/plain'
) {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Open print-ready printable window for PDF rendering
 */
export function printCalculationSheet(data: ExportReportData) {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  const dateStr = new Date(data.timestamp).toLocaleString();

  const stepsHtml =
    data.steps && data.steps.length > 0
      ? `<div class="section">
        <h3>Step-by-Step Derivation</h3>
        <ol>
          ${data.steps.map((s) => `<li>${s}</li>`).join('')}
        </ol>
      </div>`
      : '';

  const tableHtml =
    data.tableHeaders && data.tableRows && data.tableRows.length > 0
      ? `<div class="section">
        <h3>Numerical Data Table</h3>
        <table>
          <thead>
            <tr>${data.tableHeaders.map((h) => `<th>${h}</th>`).join('')}</tr>
          </thead>
          <tbody>
            ${data.tableRows.map((r) => `<tr>${r.map((c) => `<td>${c}</td>`).join('')}</tr>`).join('')}
          </tbody>
        </table>
      </div>`
      : '';

  const metadataHtml =
    data.metadata && Object.keys(data.metadata).length > 0
      ? `<div class="section">
        <h3>Parameters & Constants</h3>
        <ul>
          ${Object.entries(data.metadata)
            .map(([k, v]) => `<li><strong>${k}:</strong> ${v}</li>`)
            .join('')}
        </ul>
      </div>`
      : '';

  const html = `<!DOCTYPE html>
<html>
<head>
  <title>${data.title} - OmniCalc Pro Report</title>
  <style>
    @media print {
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      color: #0f172a;
      background: #ffffff;
      margin: 40px;
      line-height: 1.6;
    }
    .header {
      border-bottom: 2px solid #0284c7;
      padding-bottom: 15px;
      margin-bottom: 25px;
      display: flex;
      justify-content: space-between;
      align-items: flex-end;
    }
    .header h1 {
      margin: 0 0 5px 0;
      color: #0369a1;
      font-size: 24px;
    }
    .header .meta {
      font-size: 12px;
      color: #64748b;
    }
    .result-box {
      background: #f0f9ff;
      border: 1px solid #bae6fd;
      border-radius: 8px;
      padding: 16px 20px;
      margin-bottom: 25px;
    }
    .result-box .label {
      font-size: 12px;
      text-transform: uppercase;
      font-weight: bold;
      color: #0284c7;
      margin-bottom: 4px;
    }
    .result-box .value {
      font-size: 20px;
      font-family: monospace;
      font-weight: bold;
      color: #0c4a6e;
    }
    .section {
      margin-bottom: 25px;
    }
    .section h3 {
      font-size: 16px;
      color: #334155;
      border-bottom: 1px solid #e2e8f0;
      padding-bottom: 6px;
      margin-bottom: 12px;
    }
    ol, ul {
      padding-left: 20px;
      margin: 0;
      font-size: 14px;
    }
    li {
      margin-bottom: 6px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 13px;
      font-family: monospace;
    }
    th, td {
      border: 1px solid #cbd5e1;
      padding: 8px 12px;
      text-align: left;
    }
    th {
      background: #f8fafc;
      color: #475569;
    }
    .footer {
      margin-top: 40px;
      border-top: 1px solid #e2e8f0;
      padding-top: 10px;
      font-size: 11px;
      color: #94a3b8;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <h1>${data.title}</h1>
      <div class="meta">Engine: <strong>${data.engine}</strong> • Generated: ${dateStr}</div>
    </div>
    <div style="font-weight: bold; color: #0284c7; font-size: 14px;">OmniCalc Pro</div>
  </div>

  <div class="result-box">
    <div class="label">Input Specification</div>
    <div style="font-family: monospace; font-size: 14px; margin-bottom: 8px;">${data.inputDescription}</div>
    <div class="label">Computed Outcome</div>
    <div class="value">${data.resultSummary}</div>
  </div>

  ${metadataHtml}
  ${stepsHtml}
  ${tableHtml}

  <div class="footer">
    Generated with OmniCalc Pro Enterprise Mathematical Suite • www.omnicalc.pro
  </div>

  <script>
    window.onload = function() {
      window.print();
    };
  </script>
</body>
</html>`;

  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();
}
